import {
  AlertTriangle,
  Boxes,
  Building2,
  Clock,
  DollarSign,
  FileCode,
  Gauge,
  Hourglass,
  KeyRound,
  MapPin,
  Percent,
  Phone,
  QrCode,
  Receipt,
  Smartphone,
  Star,
  Store,
  Timer,
  Zap,
} from 'lucide-react';
import { SettingMeta } from './types';

export const fmt = (n: number) => n.toLocaleString('uz-UZ');

export const HIDDEN_FROM_GRID_KEYS = new Set([
  'didox_user_key',
  'didox_api_url',
  'soliq_key_path',
  'soliq_key_password_enc',
  'soliq_auth_token',
  'soliq_token_expires_at',
  'soliq_operator_tin',
  'oferta_pdf_url',
]);

/** 100% Complete metadata dictionary for EVERY setting key in backend */
export const SETTINGS_METADATA: Record<string, SettingMeta> = {
  // ── 1. Finance & Economics ──
  commission_rate_default: {
    tab: 'finance',
    category: 'Komissiya Siyosati',
    label: 'Standart platforma komissiyasi',
    unit: '%',
    min: 0,
    max: 100,
    icon: Percent,
    hint: "Yangi buyurtmalarga qo'llanadigan standart vositachilik komissiyasi foizi (Standart: 12%).",
  },
  click_fee_percent: {
    tab: 'finance',
    category: 'Ekvayring & To\'lovlar',
    label: 'Click ekvayring to\'lov haqi',
    unit: '%',
    min: 0,
    max: 10,
    icon: DollarSign,
    hint: "Onlayn karta orqali to'lovlarda Click/Payme shlyuzlari ushlab qoladigan xarajat foizi.",
  },
  payout_fee_percent: {
    tab: 'finance',
    category: 'Ekvayring & To\'lovlar',
    label: 'Seller kartasiga pul yechish (Payout) haqi',
    unit: '%',
    min: 0,
    max: 10,
    icon: DollarSign,
    hint: "Sotuvchi o'z daromadini bank kartasiga yechib olayotganda bank ushlab qoladigan foiz.",
  },
  min_order_total: {
    tab: 'finance',
    category: 'Buyurtma Parametrlari',
    label: 'Minimal buyurtma summasi',
    unit: "so'm",
    min: 0,
    icon: DollarSign,
    hint: "Xaridor do'kondan buyurtma berishi mumkin bo'lgan eng kam savat summasi (0 = cheklovsiz).",
  },
  debt_due_days: {
    tab: 'finance',
    category: 'Qarzdorlik Nazorati',
    label: 'Naqd komissiya qarzini to\'lash muddati',
    unit: 'kun',
    min: 1,
    max: 90,
    icon: Clock,
    hint: "Naqd savdo komissiyasini platformaga to'lash uchun sellerga beriladigan maksimal muhlat.",
  },
  settlement_hours: {
    tab: 'finance',
    category: 'Buyurtma Parametrlari',
    label: 'Buyurtma muzlatish (Settlement) vaqti',
    unit: 'soat',
    min: 0,
    max: 168,
    icon: Hourglass,
    hint: "Buyurtma yetkazilgach, mijoz e'tiroz bildirmasa, mablag' sellerning yechish balansiga o'tish vaqti.",
  },

  // ── 2. Legal & Soliq (Didox) ──
  platform_legal_name: {
    tab: 'legal',
    category: 'Operator Yuridik Shaxsi',
    label: 'Operator (Platforma egasi) rasmiy nomi',
    icon: Building2,
    hint: 'Barcha shartnoma, oferta va elektron hisob-fakturalarda ko\'rsatiladigan rasmiy korxona nomi ("TILAV" MCHJ).',
  },
  platform_stir: {
    tab: 'legal',
    category: 'Operator Yuridik Shaxsi',
    label: 'Operator STIR (INN) raqami',
    icon: Building2,
    hint: "Operator korxonasining 9 xonali davlat soliq identifikatsiya raqami (313296455).",
  },
  support_phone: {
    tab: 'legal',
    category: 'Operator Yuridik Shaxsi',
    label: 'Operator rasmiy aloqa telefoni',
    icon: Phone,
    hint: "Ilova va ommaviy ofertada ko'rsatiladigan rasmiy qo'llab-quvvatlash telefon raqami (+998 77 742 23 02).",
  },
  soliq_operator_tin: {
    tab: 'legal',
    category: 'Davlat Soliq & E-IMZO Integratsiyasi',
    label: 'Operator MChJ STIRi',
    icon: Building2,
    hint: "Platforma egasi bo'lgan korxona STIRi (masalan: 313296455).",
  },
  soliq_auth_token: {
    tab: 'legal',
    category: 'Davlat Soliq & E-IMZO Integratsiyasi',
    label: 'Soliq API Sessiya Tokeni (Bearer)',
    isSecret: true,
    icon: KeyRound,
    hint: "Soliq portalidagi faol sessiya/avtorizatsiya tokeni. E-IMZO orqali olinadi yoki qo'lda kiritiladi.",
  },
  soliq_token_expires_at: {
    tab: 'legal',
    category: 'Davlat Soliq & E-IMZO Integratsiyasi',
    label: 'Soliq tokeni amal qilish muddati',
    icon: Clock,
    hint: "Joriy Soliq sessiya tokenining tugash vaqti (ISO timestamp).",
  },
  soliq_key_path: {
    tab: 'legal',
    category: 'Davlat Soliq & E-IMZO Integratsiyasi',
    label: 'E-IMZO (.pfx) kalit fayli yo\'li',
    icon: FileCode,
    hint: "Serverda saqlangan rasmiy E-IMZO kalit konteyneri joylashuvi.",
  },

  // ── 3. Fiscal & Cheklar ──
  fiscal_mode: {
    tab: 'fiscal',
    category: 'Fiskallash Tartibi',
    label: 'Fiskal cheklar generatsiya rejimi',
    icon: Receipt,
    hint: 'Davlat Soliq Qo\'mitasi (OFD)ga elektron fiskal chek yuborish tartibi.',
    options: [
      {
        value: 'off',
        label: 'Off — Chek yaratilmaydi',
        desc: 'Fiskallash to\'liq o\'chirilgan (Test va ishlab chiqish rejimi)',
      },
      {
        value: 'collect',
        label: 'Collect — Cheklar yig\'iladi, yuborilmaydi',
        desc: 'Chek ma\'lumotlari bazada saqlanadi, lekin OFDga yuborilmaydi',
      },
      {
        value: 'live',
        label: 'Live — OFDga jonli yuboriladi',
        desc: 'Har bir buyurtma uchun avtomatik QR-kodli rasmiy fiskal chek beriladi',
      },
    ],
  },
  vat_rate_percent: {
    tab: 'fiscal',
    category: 'Soliq Stavkalari',
    label: 'QQS (НДС) stavkasi',
    unit: '%',
    min: 0,
    max: 20,
    icon: Percent,
    hint: "O'zbekiston Respublikasi bo'yicha amaldagi QQS foizi (12%).",
  },
  delivery_mxik_code: {
    tab: 'fiscal',
    category: 'Tasnif & MXIK',
    label: 'Yetkazib berish xizmati MXIK kodi',
    icon: FileCode,
    hint: 'Kuryerlik va yetkazib berish xizmati uchun Tasnif Soliq MXIK kodi (masalan: 05320001001000000).',
  },

  // ── 4. Risk & Anti-Fraud ──
  risk_low_rating_threshold: {
    tab: 'risk',
    category: 'Kuryer & Xizmat Sifati',
    label: 'Kuryer past baho xavf chegarasi',
    unit: 'yulduz',
    min: 1,
    max: 5,
    icon: Star,
    hint: 'Agar mijoz kuryerga ushbu yoki undan past baho (masalan 1 yoki 2 yulduz) qo\'ysa, tizim kuryerni avtomatik tekshiruv (Risk Flag) ro\'yxatiga kiritadi.',
  },
  risk_delivered_max_distance_m: {
    tab: 'risk',
    category: 'Lokatsiya & GPS Nazorati',
    label: '"Yetkazildi" bosishda mijoz manzilidan max masofa',
    unit: 'metr',
    min: 10,
    max: 5000,
    icon: MapPin,
    hint: 'Kuryer buyurtmani yakunlash (Yetkazildi) tugmasini bosganda, mijoz tanlagan manzildan eng ko\'pi bilan necha metr uzoqda bo\'lishi mumkin.',
  },
  risk_evidence_max_accuracy_m: {
    tab: 'risk',
    category: 'Lokatsiya & GPS Nazorati',
    label: 'GPS aniqligi (Accuracy) ruxsat chegarasi',
    unit: 'metr',
    min: 5,
    max: 200,
    icon: Gauge,
    hint: 'Kuryer smartfonidagi GPS aniqligi ushbu masofadan noaniq bo\'lsa (masalan 50m dan yomon), joylashuv noaniq deb qabul qilinadi.',
  },
  risk_pickup_max_distance_m: {
    tab: 'risk',
    category: 'Lokatsiya & GPS Nazorati',
    label: '"Do\'kondan oldi" bosishda do\'kondan max masofa',
    unit: 'metr',
    min: 10,
    max: 5000,
    icon: Store,
    hint: 'Kuryer tovarlarni do\'kondan qabul qilib olganda do\'kon binosidan maksimal qancha masofada bo\'lishi mumkin.',
  },
  risk_address_pin_max_distance_m: {
    tab: 'risk',
    category: 'Mijoz Manzili Nazorati',
    label: 'Mijoz manzil pini va GPS masofa chegarasi',
    unit: 'metr',
    min: 0,
    max: 10000,
    icon: MapPin,
    hint: 'Mijoz xaritada belgilagan yetkazish nuqtasi bilan uning real GPS lokatsiyasi orasidagi farq (0 = o\'chirilgan).',
  },
  risk_shop_relocation_max_m: {
    tab: 'risk',
    category: 'Do\'kon Xavfsizligi',
    label: 'Faol do\'kon koordinatasi siljish chegarasi',
    unit: 'metr',
    min: 50,
    max: 5000,
    icon: Store,
    hint: 'Faol yoki buyurtmalari bor do\'kon o\'z manzilini bu masofadan ko\'proq siljitsa, shubhali faoliyat sifatida adminlarga xabar beriladi.',
  },
  risk_impossible_speed_kmh: {
    tab: 'risk',
    category: 'Harakat & Soxta GPS',
    label: 'Imkonsiz tezlik (Teleportatsiya) chegarasi',
    unit: 'km/soat',
    min: 30,
    max: 300,
    icon: Zap,
    hint: 'Agar kuryer ikki nuqta orasida bu tezlikdan yuqori masofa bosib o\'tsa, soxta GPS (Fake Location) xavf signali yoqiladi.',
  },
  risk_impossible_min_segment_m: {
    tab: 'risk',
    category: 'Harakat & Soxta GPS',
    label: 'Tezlik tekshiruvi uchun minimal oraliq',
    unit: 'metr',
    min: 10,
    max: 1000,
    icon: MapPin,
    hint: 'Tezlik tekshiruvi hisoblanishi uchun kuryer kamida shuncha metr masofani bosib o\'tgan bo\'lishi kerak.',
  },
  risk_device_max_accounts: {
    tab: 'risk',
    category: 'Akkauntlar & Anti-Abuse',
    label: 'Bitta qurilmadagi maksimal akkaunt soni',
    unit: 'ta',
    min: 1,
    max: 20,
    icon: Smartphone,
    hint: 'Bitta telefondan haftasiga ko\'p sonli akkaunt ochish yoki promo-kodlarni suiiste\'mol qilishni cheklovchi limit.',
  },
  risk_ping_min_interval_sec: {
    tab: 'risk',
    category: 'GPS Marshrut',
    label: 'Kuryer GPS treki ping oralig\'i',
    unit: 'soniya',
    min: 1,
    max: 60,
    icon: Timer,
    hint: 'Yetkazib berish jarayonida kuryer smartfonidan serverga GPS koordinatalari necha soniyada bir marta yangilanib yuboriladi.',
  },
  risk_ping_retention_days: {
    tab: 'risk',
    category: 'Audit & Saqlash',
    label: 'Kuryer GPS treki saqlash muddati',
    unit: 'kun',
    min: 1,
    max: 365,
    icon: Clock,
    hint: 'GPS marshrut koordinatalari bazada necha kun saqlanadi.',
  },
  risk_qr_handshake_enabled: {
    tab: 'risk',
    category: 'Tasdiqlash Mexanizmlari',
    label: 'QR-kod orqali topshirish tasdig\'i',
    icon: QrCode,
    hint: '1 = Kuryer xaridorga tovar berganda QR skaner qilish talab qilinadi, 0 = Standart PIN tasdiq.',
    options: [
      { value: '1', label: '1 — QR-kod tasdig\'i majburiy' },
      { value: '0', label: '0 — Standart PIN / tugmacha tasdig\'i' },
    ],
  },

  // ── 5. Inventory & Mahsulotlar ──
  expiry_warning_days: {
    tab: 'inventory',
    category: 'Yaroqlilik Muddati',
    label: 'Yaroqlilik muddati ogohlantirish vaqti',
    unit: 'kun',
    min: 1,
    max: 90,
    icon: Clock,
    hint: 'Mahsulotning yaroqlilik muddati tugashiga shuncha kun qolganda do\'konga va adminga ogohlantirish xabari boradi.',
  },
  expiry_critical_days: {
    tab: 'inventory',
    category: 'Yaroqlilik Muddati',
    label: 'Yaroqlilik muddati kritik chegarasi',
    unit: 'kun',
    min: 1,
    max: 30,
    icon: AlertTriangle,
    hint: 'Muddati tugashiga shuncha kun qolgan mahsulotlar avtomatik tarzda vitrinadan yashiriladi va sotuvi to\'xtatiladi.',
  },
  low_stock_warning_default: {
    tab: 'inventory',
    category: 'Ombor Qoldiqlari',
    label: 'Kam qolgan tovar ogohlantirish soni',
    unit: 'dona',
    min: 1,
    max: 100,
    icon: Boxes,
    hint: 'Mahsulot qoldig\'i ushbu miqdordan kamaysa, sotuvchiga tovar tugayotgani haqida bildirishnoma boradi.',
  },
  low_stock_critical_default: {
    tab: 'inventory',
    category: 'Ombor Qoldiqlari',
    label: 'Tugash arafasidagi kritik qoldiq soni',
    unit: 'dona',
    min: 0,
    max: 50,
    icon: Boxes,
    hint: 'Mahsulot qoldig\'i ushbu songa tushganda omborda tovar tugayotganlik xavfi belgilanadi.',
  },
};
